### ISSUE TITLE
Negative Array Indices

### ISSUE THREAD

**Issue by asp3** [dshepsis/ExpressionGenerator#1]
When generating expressions with arrays, many of them simplify to a negative array index

**Comment by dshepsis** [comment]
Hi, thanks for the report. I've made a commit which mostly fixes the issue.  Array indices are now adjusted to be within range. However, it will not be able to make adjustments when there is a nested Array within the index expression. This is done for the same reason as why the expression evaluator cannot give the results of array expressions in general.
